/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SafeRouteImport } from './routes/safe'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SafeTransactionsRouteImport } from './routes/safe.transactions'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeRoute = SafeRouteImport.update({
  id: '/safe',
  path: '/safe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeTransactionsRoute = SafeTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => SafeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/safe': typeof SafeRouteWithChildren
  '/wallet': typeof WalletRoute
  '/safe/transactions': typeof SafeTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/safe': typeof SafeRouteWithChildren
  '/wallet': typeof WalletRoute
  '/safe/transactions': typeof SafeTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/safe': typeof SafeRouteWithChildren
  '/wallet': typeof WalletRoute
  '/safe/transactions': typeof SafeTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/safe' | '/wallet' | '/safe/transactions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/safe' | '/wallet' | '/safe/transactions'
  id: '__root__' | '/' | '/safe' | '/wallet' | '/safe/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SafeRoute: typeof SafeRouteWithChildren
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safe': {
      id: '/safe'
      path: '/safe'
      fullPath: '/safe'
      preLoaderRoute: typeof SafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safe/transactions': {
      id: '/safe/transactions'
      path: '/transactions'
      fullPath: '/safe/transactions'
      preLoaderRoute: typeof SafeTransactionsRouteImport
      parentRoute: typeof SafeRoute
    }
  }
}

interface SafeRouteChildren {
  SafeTransactionsRoute: typeof SafeTransactionsRoute
}

const SafeRouteChildren: SafeRouteChildren = {
  SafeTransactionsRoute: SafeTransactionsRoute,
}

const SafeRouteWithChildren = SafeRoute._addFileChildren(SafeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SafeRoute: SafeRouteWithChildren,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
